twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
        - 'form_theme.html.twig' # Custom theme
when@test:
    twig:
        strict_variables: true


